# Generated by Django 3.0.2 on 2020-01-23 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date of purchase'),
        ),
    ]
