# Generated by Django 3.0.2 on 2020-01-23 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200123_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date of purchase'),
        ),
    ]
